//
// Created by whyiskra on 2025-05-24.
//

#pragma once

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    MOD_CLK_CPU_FREQ_8MHZ,
    MOD_CLK_CPU_FREQ_16MHZ,
    MOD_CLK_CPU_FREQ_32MHZ,
    MOD_CLK_CPU_FREQ_64MHZ,
    MOD_CLK_CPU_FREQ_96MHZ,
} mod_clk_cpu_freq_t;

typedef enum {
    MOD_CLK_PERIPHERAL_CAN1 = 0,
    MOD_CLK_PERIPHERAL_CAN2 = 1,
    MOD_CLK_PERIPHERAL_USB = 2,
    MOD_CLK_PERIPHERAL_EEPROM_CNTRL = 3,
    MOD_CLK_PERIPHERAL_RST_CLK = 4,
    MOD_CLK_PERIPHERAL_DMA = 5,
    MOD_CLK_PERIPHERAL_UART1 = 6,
    MOD_CLK_PERIPHERAL_UART2 = 7,
    MOD_CLK_PERIPHERAL_SPI1 = 8,
    MOD_CLK_PERIPHERAL_MIL_STD_1553B1 = 9,
    MOD_CLK_PERIPHERAL_MIL_STD_1553B2 = 10,
    MOD_CLK_PERIPHERAL_POWER = 11,
    MOD_CLK_PERIPHERAL_WWDT = 12,
    MOD_CLK_PERIPHERAL_IWDT = 13,
    MOD_CLK_PERIPHERAL_TIMER1 = 14,
    MOD_CLK_PERIPHERAL_TIMER2 = 15,
    MOD_CLK_PERIPHERAL_TIMER3 = 16,
    MOD_CLK_PERIPHERAL_ADC = 17,
    MOD_CLK_PERIPHERAL_DAC = 18,
    MOD_CLK_PERIPHERAL_TIMER4 = 19,
    MOD_CLK_PERIPHERAL_SPI2 = 20,
    MOD_CLK_PERIPHERAL_PORTA = 21,
    MOD_CLK_PERIPHERAL_PORTB = 22,
    MOD_CLK_PERIPHERAL_PORTC = 23,
    MOD_CLK_PERIPHERAL_PORTD = 24,
    MOD_CLK_PERIPHERAL_PORTE = 25,
    MOD_CLK_PERIPHERAL_ARINC429R = 26,
    MOD_CLK_PERIPHERAL_BKP = 27,
    MOD_CLK_PERIPHERAL_ARINC429T = 28,
    MOD_CLK_PERIPHERAL_PORTF = 29,
    MOD_CLK_PERIPHERAL_EXT_BUS_CNTRL = 30,
    MOD_CLK_PERIPHERAL_SPI3 = 31,
} mod_clk_peripheral_t;

void clk_init(void);

int clk_set_cpu_freq(mod_clk_cpu_freq_t);
uint32_t clk_get_cpu_freq(void);

int clk_en_peripheral(mod_clk_peripheral_t, bool);
